title = "FS-UAE Launcher"
name = "fs-uae-launcher"
py_name = "fs_uae_launcher"
tar_name = "fs-uae-launcher"
version = "9.8.7dummy"
author = "Frode Solheim"
author_email = "frode@fs-uae.net"
package_map = {
    "amitools": ".",
    "arcade": ".",
    "fsbc": ".",
    "fsboot": ".",
    "fscore": ".",
    "fsgamesys": ".",
    "fspy": ".",
    "fstd": ".",
    "fsui": ".",
    "launcher": ".",
    "oyoyo": ".",
    "workspace": ".",
}
packages = sorted(package_map.keys())
scripts = ["fs-uae-launcher"]
extra_dist = [
    "data/Fonts/SairaCondensed-Bold.ttf",
    "data/Fonts/SairaCondensed-Regular.ttf",
    "data/Fonts/SairaSemiCondensed-Medium.ttf",
    "data/Fonts/SairaCondensed-Medium.ttf",
    "data/Fonts/SairaCondensed-SemiBold.ttf",
    "docs/compiling.md",
    "docs/file-database.md",
    "src/Makefile",
    "src/icons/colorizeicon.sh",
    "src/icons/glowicon.sh",
    "src/icons/TitleBarMinimize.svg",
    "src/icons/TitleBarMaximize.svg",
    "src/icons/TitleBarClose.svg",
    "src/icons/TitleBarMenu.svg",
    "src/icons/tango/Makefile",
    "src/icons/tango/README.md",
    "src/icons/tango/64/Makefile",
    "src/icons/tango/64/drive-harddisk-3.svg",
    "src/icons/tango/64/drive-harddisk-4.svg",
    "src/icons/tango/64/drive-harddisk.svg",
    "src/icons/tango/64/drive-harddisk-2.svg",
    "src/icons/tango/overlays/system-search.png",
    "src/icons/amigaforever/volumeoverlays/AmigaForever.png",
    "src/icons/adwaita/Makefile",
    "src/icons/adwaita/COPYING",
    "src/icons/adwaita/COPYING_LGPL",
    "src/icons/adwaita/README.md",
    "src/icons/adwaita/COPYING_CCBYSA3",
    "src/icons/adwaita/64/Makefile",
    "src/icons/adwaita/64/application-x-firmware.png",
    "src/icons/Makefile",
    "src/icons/gnome/volume-overlays/applications-games.png",
    "src/icons/gnome/overlays/applications-games.png",
    "src/icons/gnome/overlays/preferences-system.png",
    "src/icons/humanity/Makefile",
    "src/icons/humanity/README.md",
    "src/icons/humanity/64/application-x-lha.svg",
    "src/icons/humanity/64/applications-simulation.svg",
    "src/icons/humanity/64/input-mouse.svg",
    "src/icons/humanity/64/system-file-manager-3.svg",
    "src/icons/humanity/64/menu-editor.svg",
    "src/icons/humanity/64/system-file-manager-6.svg",
    "src/icons/humanity/64/Makefile",
    "src/icons/humanity/64/system-software-update-2-no-shadow.svg",
    "src/icons/humanity/64/help-contents.svg",
    "src/icons/humanity/64/edit-clear.svg",
    "src/icons/humanity/64/preview-file.svg",
    "src/icons/humanity/64/accessories-calculator.svg",
    "src/icons/humanity/64/clock.svg",
    "src/icons/humanity/64/applications-graphics.svg",
    "src/icons/humanity/64/audio-card.svg",
    "src/icons/humanity/64/stock_person.svg",
    "src/icons/humanity/64/system-file-manager-5.svg",
    "src/icons/humanity/64/extension.svg",
    "src/icons/humanity/64/system-file-manager-4.svg",
    "src/icons/humanity/64/system-file-manager-7.svg",
    "src/icons/humanity/64/system-software-update.svg",
    "src/icons/humanity/64/preferences-desktop-sound.svg",
    "src/icons/humanity/64/preferences-desktop-locale.svg",
    "src/icons/humanity/64/input-keyboard.svg",
    "src/icons/humanity/64/system-file-manager-1.svg",
    "src/icons/humanity/64/system-file-manager-8.svg",
    "src/icons/humanity/64/user-desktop.svg",
    "src/icons/humanity/64/video-display.svg",
    "src/icons/humanity/64/logviewer.svg",
    "src/icons/humanity/64/system-file-manager.svg",
    "src/icons/humanity/64/gnome-power-manager.svg",
    "src/icons/humanity/64/network-server.svg",
    "src/icons/humanity/64/applications-fonts.svg",
    "src/icons/humanity/64/prefs-overlay.png",
    "src/icons/humanity/64/system-software-update-2.svg",
    "src/icons/humanity/64/system-file-manager-2.svg",
    "src/icons/humanity/64/view-fullscreen.svg",
    "src/icons/humanity/64/applications-arcade.svg",
    "src/icons/humanity/overlays/applications-utilities.png",
    "src/icons/humanity/overlays/Utilities.png",
    "src/icons/humanity/overlays/preferences-system.png",
    "src/icons/humanity/overlays/system-help.png",
    "src/icons/humanity/24/media-optical.svg",
    "src/icons/humanity/24/media-floppy.svg",
    "src/icons/humanity/24/drive-harddisk.svg",
    "src/icons/shared/tango-software-update-available.png",
    "src/icons/fontawesome/Makefile",
    "src/icons/fontawesome/tabs/memory.png",
    "src/icons/fontawesome/tabs/microchip.png",
    "src/icons/fontawesome/tabs/Makefile",
    "src/icons/fontawesome/tabs/save.png",
    "src/icons/fontawesome/tabs/home.png",
    "src/icons/fontawesome/tabs/tasks.png",
    "src/icons/fontawesome/tabs/gamepad.png",
    "src/icons/fontawesome/tabs/hdd.png",
    "src/icons/fontawesome/tabs/compact-disc.png",
    "src/icons/fontawesome/16/Makefile",
    "src/icons/fontawesome/16/cog.png",
    "src/icons/fontawesome/LICENSE.txt",
    "src/icons/human/24/gnome-dev-memory.png",
    "src/icons/human/24/gnome-dev-harddisk.png",
    "src/icons/human/24/gnome-dev-floppy.png",
    "src/icons/human/24/go-home.png",
    "src/icons/human/24/gnome-dev-cdrom.png",
    "src/icons/system/utilities/checksum/tango-application-certificate.svg",
    "src/icons/system/utilities/checksum/humanity-multipart-encrypted.svg",
    "src/icons/system/utilities/checksum/tango-application-certificate.png",
    "src/icons/64/Makefile",
    "src/icons/64/fs-uae-arcade.svg",
    "src/icons/64/fs-uae-launcher.svg",
    "src/icons/overlays/fs-uae-volume_selected.png",
    "src/icons/overlays/fs-uae-volume.png",
]
