#!/usr/bin/env python3

from fsboot import setup_python_path

# setup_python_path()

from launcher.main import main

main(app="fs-uae-launcher")

# Dummy imports for cx_Freeze
import sys

sys.exit(0)

# noinspection PyUnreachableCode,PyUnresolvedReferences,PyProtectedMember
import _sysconfigdata_m_darwin_darwin

# noinspection PyUnreachableCode,PyUnresolvedReferences,PyProtectedMember
import idna.idnadata

# noinspection PyUnreachableCode,PyUnresolvedReferences,PyProtectedMember
import pkg_resources._vendor.appdirs

# noinspection PyUnreachableCode,PyUnresolvedReferences,PyProtectedMember
import pkg_resources._vendor.packaging.requirements

# noinspection PyUnreachableCode,PyUnresolvedReferences,PyProtectedMember
import pkg_resources._vendor.packaging.specifiers

# noinspection PyUnreachableCode,PyUnresolvedReferences,PyProtectedMember
import pkg_resources._vendor.packaging.version

# noinspection PyUnreachableCode,PyUnresolvedReferences,PyProtectedMember
import pkg_resources._vendor.pyparsing

# noinspection PyUnreachableCode,PyUnresolvedReferences,PyProtectedMember
import pkg_resources._vendor.six

# noinspection PyUnreachableCode,PyUnresolvedReferences,PyProtectedMember
import PyQt5.sip

import sentry_sdk.integrations
import sentry_sdk.integrations.argv
import sentry_sdk.integrations.atexit
import sentry_sdk.integrations.bottle
import sentry_sdk.integrations.celery
import sentry_sdk.integrations.dedupe
import sentry_sdk.integrations.django
import sentry_sdk.integrations.excepthook
import sentry_sdk.integrations.falcon
import sentry_sdk.integrations.flask
import sentry_sdk.integrations.logging
import sentry_sdk.integrations.modules
import sentry_sdk.integrations.sanic
import sentry_sdk.integrations.stdlib
import sentry_sdk.integrations.threading

# import sentry_sdk.integrations
import sentry_sdk.integrations.aiohttp
import sentry_sdk.integrations.argv
import sentry_sdk.integrations.asgi
import sentry_sdk.integrations.atexit
import sentry_sdk.integrations.aws_lambda
import sentry_sdk.integrations.beam
import sentry_sdk.integrations.boto3
import sentry_sdk.integrations.bottle
import sentry_sdk.integrations.celery
import sentry_sdk.integrations.chalice
import sentry_sdk.integrations.dedupe
import sentry_sdk.integrations.django.asgi
import sentry_sdk.integrations.django
# import sentry_sdk.integrations.django.middleware
# import sentry_sdk.integrations.django.templates
# import sentry_sdk.integrations.django.transactions
# import sentry_sdk.integrations.django.views
import sentry_sdk.integrations.excepthook
import sentry_sdk.integrations.executing
import sentry_sdk.integrations.falcon
import sentry_sdk.integrations.flask
import sentry_sdk.integrations.gcp
import sentry_sdk.integrations.gnu_backtrace
import sentry_sdk.integrations.logging
import sentry_sdk.integrations.modules
import sentry_sdk.integrations.pure_eval
import sentry_sdk.integrations.pyramid
import sentry_sdk.integrations.redis
import sentry_sdk.integrations.rq
import sentry_sdk.integrations.sanic
import sentry_sdk.integrations.serverless
import sentry_sdk.integrations.spark
# import sentry_sdk.integrations.spark.spark_driver
# import sentry_sdk.integrations.spark.spark_worker
import sentry_sdk.integrations.sqlalchemy
import sentry_sdk.integrations.stdlib
import sentry_sdk.integrations.threading
import sentry_sdk.integrations.tornado
import sentry_sdk.integrations.trytond
import sentry_sdk.integrations._wsgi_common
import sentry_sdk.integrations.wsgi
