data = ../../../../data
colorizeicon = ../../colorizeicon.sh

launcher_res = ../../../../launcher/res

all:
	mkdir -p ${launcher_res}/32x32/

	${colorizeicon} '#555555' compact-disc.png ${launcher_res}/32x32/media-optical.png
	${colorizeicon} '#555555' gamepad.png ${launcher_res}/32x32/applications-games.png
	${colorizeicon} '#555555' hdd.png ${launcher_res}/32x32/drive-harddisk.png
	${colorizeicon} '#555555' home.png ${launcher_res}/32x32/go-home.png
	${colorizeicon} '#555555' memory.png ${launcher_res}/32x32/audio-card.png
	${colorizeicon} '#555555' microchip.png ${launcher_res}/32x32/application-x-firmware.png
	${colorizeicon} '#555555' save.png ${launcher_res}/32x32/media-floppy.png
	${colorizeicon} '#555555' tasks.png ${launcher_res}/32x32/system-shutdown.png
