data = ../../../../data
glowicon = ../../glowicon.sh

icons = ${data}/Icons
system = ${icons}/System
prefs = ${system}/Prefs
tools = ${system}/Tools
utilities = ${system}/Utilities

all:
	mkdir -p ${icons}

	${glowicon} --base ${icons}/"Ram Disk".png \
		application-x-firmware.png
	${glowicon} --glow ${icons}/"Ram Disk"_Selected.png \
		application-x-firmware.png
