from launcher.system.prefs.advanced import Advanced
from launcher.system.prefs.appearance import Appearance
from launcher.system.prefs.arcade import Arcade
from launcher.system.prefs.controller import Controller
from launcher.system.prefs.filedatabase import FileDatabase
from launcher.system.prefs.gamedatabase import GameDatabase
from launcher.system.prefs.keyboard import Keyboard
from launcher.system.prefs.locale import Locale
from launcher.system.prefs.logging import Logging
from launcher.system.prefs.midi import MIDI
from launcher.system.prefs.mouse import Mouse
from launcher.system.prefs.netplay import NetPlay
from launcher.system.prefs.opengl import OpenGL
from launcher.system.prefs.openretro import OpenRetro
from launcher.system.prefs.overscan import Overscan
from launcher.system.prefs.plugin import Plugin
from launcher.system.prefs.power import Power
from launcher.system.prefs.privacy import Privacy
from launcher.system.prefs.screenmode import ScreenMode
from launcher.system.prefs.sound import Sound
from launcher.system.prefs.storage import Storage
from launcher.system.prefs.update import Update
from launcher.system.prefs.video import Video
from launcher.system.prefs.whdload import WHDLoad
from launcher.system.prefs.workspace import Workspace
