data = ../../../data
glowicon = ../glowicon.sh

icons = ${data}/Icons
system = ${icons}/System
prefs = ${system}/Prefs
tools = ${system}/Tools
utilities = ${system}/Utilities

all:
	mkdir -p ${system}

	${glowicon} --base ${system}/Arcade.png \
		fs-uae-arcade.svg
	${glowicon} --glow ${system}/Arcade_Selected.png \
		fs-uae-arcade.svg

	${glowicon} --base ${system}/Launcher.png \
		fs-uae-launcher.svg
	${glowicon} --glow ${system}/Launcher_Selected.png \
		fs-uae-launcher.svg
