data = ../../../../data
glowicon = ../../glowicon.sh

icons = ${data}/Icons
system = ${icons}/System
prefs = ${system}/Prefs
platforms = ${system}/Prefs/Platforms
tools = ${system}/Tools
utilities = ${system}/Utilities

all: platforms prefs system tools utilities

system:
	mkdir -p ${system}

	${glowicon} --base ${system}/Tools.png \
		system-file-manager-8.svg \
		../../gnome/overlays/preferences-system.png
	${glowicon} --glow ${system}/Tools_Selected.png \
		system-file-manager-8.svg \
		../../gnome/overlays/preferences-system.png

	${glowicon} --base ${system}/Utilities.png \
		system-file-manager-8.svg \
		../overlays/applications-utilities.png
	${glowicon} --glow ${system}/Utilities_Selected.png \
		system-file-manager-8.svg \
		../overlays/applications-utilities.png

platforms:
	mkdir -p ${prefs}

	${glowicon} --base ${prefs}/Platforms.png \
		system-file-manager-8.svg
	${glowicon} --glow ${prefs}/Platforms_Selected.png \
		system-file-manager-8.svg

	mkdir -p ${platforms}

	${glowicon} --base ${platforms}/AmstradCPC.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/AmstradCPC_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/Arcade.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/Arcade_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/Atari7800.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/Atari7800_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/AtariST.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/AtariST_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/Commodore64.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/Commodore64_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/DOS.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/DOS_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/GameBoy.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/GameBoy_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/GameBoyAdvance.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/GameBoyAdvance_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/GameBoyColor.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/GameBoyColor_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/MasterSystem.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/MasterSystem_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/MegaDrive.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/MegaDrive_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/Neo-Geo.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/Neo-Geo_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/Nintendo.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/Nintendo_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/PlayStation.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/PlayStation_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/SuperNintendo.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/SuperNintendo_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/TurboGrafx-16.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/TurboGrafx-16_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/TurboGrafx-CD.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/TurboGrafx-CD_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${platforms}/ZXSpectrum.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${platforms}/ZXSpectrum_Selected.png \
		help-contents.svg prefs-overlay.png


prefs:
	mkdir -p ${system}

	${glowicon} --base ${system}/Prefs.png \
		system-file-manager-8.svg \
		../overlays/system-help.png
	${glowicon} --glow ${system}/Prefs_Selected.png \
		system-file-manager-8.svg \
		../overlays/system-help.png

	mkdir -p ${prefs}

	${glowicon} --base ${prefs}/Advanced.png \
		menu-editor.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Advanced_Selected.png \
		menu-editor.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Appearance.png \
		applications-graphics.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Appearance_Selected.png \
		applications-graphics.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Arcade.png \
		applications-arcade.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Arcade_Selected.png \
		applications-arcade.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Controller.png \
		applications-simulation.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Controller_Selected.png \
		applications-simulation.svg prefs-overlay.png

	# ${glowicon} --base ${prefs}/Directory.png \
	# 	system-file-manager-8.svg prefs-overlay.png
	# ${glowicon} --glow ${prefs}/Directory_Selected.png \
	# 	system-file-manager-8.svg prefs-overlay.png

	${glowicon} --base ${prefs}/FileDatabase.png \
		network-server.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/FileDatabase_Selected.png \
		network-server.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Font.png \
		applications-fonts.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Font_Selected.png \
		applications-fonts.svg prefs-overlay.png

	${glowicon} --base ${prefs}/GameDatabase.png \
		network-server.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/GameDatabase_Selected.png \
		network-server.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Keyboard.png \
		input-keyboard.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Keyboard_Selected.png \
		input-keyboard.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Locale.png \
		preferences-desktop-locale.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Locale_Selected.png \
		preferences-desktop-locale.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Logging.png \
		logviewer.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Logging_Selected.png \
		logviewer.svg prefs-overlay.png

	${glowicon} --base ${prefs}/MIDI.png \
		audio-card.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/MIDI_Selected.png \
		audio-card.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Mouse.png \
		input-mouse.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Mouse_Selected.png \
		input-mouse.svg prefs-overlay.png

	${glowicon} --base ${prefs}/NetPlay.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/NetPlay_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${prefs}/OpenGL.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/OpenGL_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${prefs}/OpenRetro.png \
		help-contents.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/OpenRetro_Selected.png \
		help-contents.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Overscan.png \
		view-fullscreen.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Overscan_Selected.png \
		view-fullscreen.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Plugin.png \
		extension.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Plugin_Selected.png \
		extension.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Power.png \
		gnome-power-manager.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Power_Selected.png \
		gnome-power-manager.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Privacy.png \
		stock_person.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Privacy_Selected.png \
		stock_person.svg prefs-overlay.png

	${glowicon} --base ${prefs}/ScreenMode.png \
		view-fullscreen.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/ScreenMode_Selected.png \
		view-fullscreen.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Sound.png \
		preferences-desktop-sound.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Sound_Selected.png \
		preferences-desktop-sound.svg prefs-overlay.png

	# ${glowicon} --base ${prefs}/Storage.png \
	# 	system-file-manager-8.svg prefs-overlay.png
	# ${glowicon} --glow ${prefs}/Storage_Selected.png \
	# 	system-file-manager-8.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Video.png \
		video-display.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Video_Selected.png \
		video-display.svg prefs-overlay.png

	${glowicon} --base ${prefs}/WHDLoad.png \
		application-x-lha.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/WHDLoad_Selected.png \
		application-x-lha.svg prefs-overlay.png

	${glowicon} --base ${prefs}/Workspace.png \
		user-desktop.svg prefs-overlay.png
	${glowicon} --glow ${prefs}/Workspace_Selected.png \
		user-desktop.svg prefs-overlay.png

tools:
	mkdir -p ${tools}

	${glowicon} --base ${tools}/Calculator.png \
		accessories-calculator.svg
	${glowicon} --glow ${tools}/Calculator_Selected.png \
		accessories-calculator.svg

	${glowicon} --base ${tools}/DatabaseUpdater.png \
		system-software-update-2.svg
	${glowicon} --glow ${tools}/DatabaseUpdater_Selected.png \
		system-software-update-2-no-shadow.svg

	# ${glowicon} --base ${utilities}/FileScanner.png \
	# 	preview-file.svg
	# ${glowicon} --glow ${utilities}/FileScanner_Selected.png \
	# 	preview-file.svg


utilities:
	mkdir -p ${utilities}

	# ${glowicon} --base ${utilities}/Checksum.png \
	# 	clock.svg
	# ${glowicon} --glow ${utilities}/Checksum_Selected.png \
	# 	clock.svg

	${glowicon} --base ${utilities}/Clock.png \
		clock.svg
	${glowicon} --glow ${utilities}/Clock_Selected.png \
		clock.svg

	${glowicon} --base ${utilities}/MultiView.png \
		preview-file.svg
	${glowicon} --glow ${utilities}/MultiView_Selected.png \
		preview-file.svg
