data = ../../../../data
colorizeicon = ../../colorizeicon.sh

launcher_data = ../../../../launcher/data

all:
	mkdir -p ${launcher_data}/16x16/

	${colorizeicon} '#555555' cog.png ${launcher_data}/16x16/settings.png
