data = ../../../../data
colorizeicon = ../../colorizeicon.sh

launcher_res = ../../../../launcher/res

all:
	mkdir -p ${launcher_res}/16x16/

	${colorizeicon} '#555555' cog.png ${launcher_res}/16x16/settings.png
