from system.prefs.advanced import Advanced
from system.prefs.appearance import Appearance
from system.prefs.arcade import Arcade
from system.prefs.controllers import Controllers
from system.prefs.filedatabase import FileDatabase
from system.prefs.gamedatabase import GameDatabase
from system.prefs.keyboard import Keyboard
from system.prefs.locale import Locale
from system.prefs.logging import Logging
from system.prefs.midi import MIDI
from system.prefs.mouse import Mouse
from system.prefs.netplay import NetPlay
from system.prefs.opengl import OpenGL
from system.prefs.openretro import OpenRetro
from system.prefs.overscan import Overscan
from system.prefs.plugin import Plugin
from system.prefs.power import Power
from system.prefs.privacy import Privacy
from system.prefs.screenmode import ScreenMode
from system.prefs.sound import Sound
from system.prefs.storage import Storage
from system.prefs.updates import Updates
from system.prefs.video import Video
from system.prefs.whdload import WHDLoad
from system.prefs.workspace import Workspace
