name: Linux
on:
  push:
    branches:
      - master
      - dev
      - stable
  pull_request:
    branches:
      - master
      - dev
      - stable
jobs:
  x86-64:
    runs-on: ubuntu-18.04
    steps:

      - name: Install deb packages
        run: >-
          sudo apt install
          dos2unix
          gettext

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pipenv

      - name: Run pipenv install
        run: |
          pipenv install --deploy

      - name: Download pyinstaller source
        run: |
          wget https://github.com/pyinstaller/pyinstaller/releases/download/v4.2/PyInstaller-4.2.tar.gz
          echo "f5c0eeb2aa663cce9a5404292c0195011fa500a6501c873a466b2e8cad3c950c *PyInstaller-4.2.tar.gz" > SHA256SUMS
          shasum -c SHA256SUMS
          tar xf PyInstaller-4.2.tar.gz

      - name: Compile new bootloader for pyinstaller
        run: |
          cd pyinstaller-4.2/bootloader
          CC="gcc -no-pie" ./waf all

      - name: Replace pyinstaller with custom version
        run: |
          pipenv uninstall pyinstaller
          pipenv install `pwd`/pyinstaller-4.2

      - name: Update version
        run: |
          fsbuild/version --update --auto

      - name: Bootstrap
        run: fsbuild/bootstrap

      - name: Build
        run: |
          pipenv run fsbuild/build

      - name: Bundle
        run: |
          pipenv run fsbuild/bundle

      - name: Archive
        run: |
          fsbuild/archive

      - uses: actions/upload-artifact@v2
        with:
          name: Linux_x86-64
          path: fsbuild/_dist/*

      - name: Upload build to Dropbox folder
        if: >-
          github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/dev' ||
          github.ref == 'refs/heads/stable'
        run: |
          python3 -m pip install dropbox
          fsbuild/upload
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
