name: Linux

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
        default: ubuntu-24.04
      artifact-name:
        required: true
        type: string
        default: linux

jobs:
  linux:
    runs-on: ${{ inputs.runner }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install packages
        run: sudo apt install gettext

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.9"

      - name: Set up Python
        run: uv python install

      - name: Run uv sync
        run: uv sync

      - name: Build
        run: uv run python -m build all

      - uses: actions/upload-artifact@v4
        with:
          name: "${{ inputs.artifact-name }}-${{ github.run_id }}"
          path: build/_dist/*
