name: Linux

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
        default: ubuntu-24.04

jobs:
  linux:
    runs-on: ${{ inputs.runner }}

    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
      DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
      DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install packages
        run: sudo apt install gettext

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.9"

      - name: Set up Python
        run: uv python install

      - name: Run uv sync
        run: uv sync

      - name: Build
        run: uv run python -m build all

      - uses: actions/upload-artifact@v4
        with:
          path: build/_dist/*

      - name: Upload to Dropbox
        if: >-
          env.DROPBOX_REFRESH_TOKEN != null && (
            github.ref == 'refs/heads/beta' ||
            github.ref == 'refs/heads/dev' ||
            github.ref == 'refs/heads/main' ||
            github.ref == 'refs/heads/master' ||
            github.ref == 'refs/heads/stable' ||
            github.ref == 'refs/heads/test'
          )
        run: |
          uv run python -m build upload
