name: Source

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: 'Version to set in tarballs'
        required: false
        default: '0.0.0-edge'
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version to set in tarballs'
        required: false
        default: '0.0.0-edge'

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  Source:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.12

      - name: Set base version
        run: |
          echo "BASEVERSION_FS=${{ inputs.version }}" > BASEVERSION.FS
        if: ${{ inputs.version }}

      - name: Update version
        run: |
          fsbuild/version --update

      - name: Bootstrap
        if: hashFiles('fsbuild/bootstrap') != ''
        run: |
          fsbuild/bootstrap

      - name: Configure
        if: hashFiles('fsbuild/configure') != ''
        run: |
          fsbuild/configure

      - name: Source
        run: |
          fsbuild/source

      - name: Upload builds to artifact storage
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: Source-${{ inputs.version }}
          path: fsbuild/_dist/*
        if: github.event_name != 'pull_request'
